# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'album_element.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(180, 180)
        Form.setMinimumSize(QtCore.QSize(180, 180))
        Form.setMaximumSize(QtCore.QSize(180, 180))
        self.picture = QtWidgets.QLabel(Form)
        self.picture.setGeometry(QtCore.QRect(0, 0, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture.sizePolicy().hasHeightForWidth())
        self.picture.setSizePolicy(sizePolicy)
        self.picture.setMinimumSize(QtCore.QSize(180, 180))
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.picture_2 = QtWidgets.QLabel(Form)
        self.picture_2.setGeometry(QtCore.QRect(0, 0, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_2.sizePolicy().hasHeightForWidth())
        self.picture_2.setSizePolicy(sizePolicy)
        self.picture_2.setMinimumSize(QtCore.QSize(180, 180))
        self.picture_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 75), stop:1 rgba(200, 200, 200, 75));")
        self.picture_2.setText("")
        self.picture_2.setObjectName("picture_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 182, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name.setMinimumSize(QtCore.QSize(180, 0))
        self.name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Futura BdCn BT")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel {color: white}")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.artist = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.artist.setMinimumSize(QtCore.QSize(0, 0))
        self.artist.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Futura Lt BT")
        font.setPointSize(12)
        self.artist.setFont(font)
        self.artist.setStyleSheet("QLabel {color: white}")
        self.artist.setAlignment(QtCore.Qt.AlignCenter)
        self.artist.setObjectName("artist")
        self.verticalLayout.addWidget(self.artist)
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(0, 0, 180, 180))
        self.button.setMinimumSize(QtCore.QSize(180, 180))
        self.button.setMaximumSize(QtCore.QSize(180, 180))
        self.button.setStyleSheet(
            "QPushButton {  background-color: rgb(0, 0, 0, 0); } QPushButton:hover {  background-color: rgb(0, 0, 0, 50); }")
        self.button.setText("")
        self.button.setObjectName("button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setText(_translate("Form", "TextLabel"))
        self.artist.setText(_translate("Form", "Porter"))
