# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'artist_element.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(100, 100)
        self.picture = QtWidgets.QLabel(Form)
        self.picture.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.button.setStyleSheet("QPushButton {background-color: rgb(0, 0, 0, 0)}")
        self.button.setText("")
        self.button.setObjectName("button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
